select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "D",
    "UP",
    "S",
    "B",
    "A",
    "C4",
    "DJ",
    "RET",
    "SIM",
    "PTH",
    "TD",
    "FIX",
    "PD",
    "PL",
    "NPY",
    "RUF",
]

target-version = "py311"

include = ["frontend/"]
