name: deta-build

run-name: Build and push to Deta Space

on:
  push:
    branches:
      - maaster
      - github-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: crosslink toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: build crate
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl --manifest-path data-scraping/Cargo.toml
      - name: Install Deta Space CLI & set SPACE_ACCESS_TOKEN environment variable
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo "$HOME/.detaspace/bin" >> $GITHUB_PATH
          echo "SPACE_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: Push changes to Deta Space
        shell: bash
        run: |
          space link --id "${{ secrets.PROJECT_ID }}"
          ls -lha
          cp data-scraping/target/x86_64-unknown-linux-musl/release/scrape_trout_stocking .
          space push
